global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:5001']
  - job_name: 'doctor-service'
    static_configs:
      - targets: ['doctor-service:5002']
  - job_name: 'appointment-service'
    static_configs:
      - targets: ['appointment-service:5003']
  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:5004']
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['host.docker.internal:5000']
