apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-config
data:
  PORT: "5004"
  MONGO_URI: "mongodb+srv://admin:admin123@cluster0.mongodb.net/medibook?retryWrites=true&w=majority"
  JWT_SECRET: "supersecretkey123"
  # Dependencies
  DOCTOR_SERVICE_URL: "http://doctor-service:5002"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: admin-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5004
        envFrom:
        - configMapRef:
            name: admin-config
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: ClusterIP
